### ISSUE TITLE
[BUG] FFZ Interaction with Scrollback

### ISSUE THREAD

**Issue by jrmann1999** [SevenTV/Extension#1018]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest nightly version

- [X] I am using the latest nightly version

### What browsers are you seeing the problem on?

Microsoft Edge

### Current Behavior

With updated stable versions of both FFZ and 7TV, twitch chats are disappearing right after they are seen.  It appears the 7TV setting that sets the scrollback to 1 line is overriding FFZ's default.  When you disable the 7TV profile in FFZ the behavior disappears.

![image](https://github.com/SevenTV/Extension/assets/1932946/25e89710-3bb4-460a-9cdf-d208c8ee9433)

### Expected Behavior

Normal chat scrollback

### Steps To Reproduce

Enable 7TV and FFZ with current stable versions.

**Comment by jrmann1999** [comment]
I changed to nightly 7TV, issue still exists.

**Comment by PualMage** [comment]
Im running this on Chrome. this problem has happened many times also, other issues with the chat have been emotes not showing up and other random problems. they are always solved by force quieting the browser and reopening any stream.

**Comment by craigbrennan24** [comment]
Apologies for bumping an old thread, but this issue of 7TV setting the scrollback to 1 in FFZ and clearing the chat as a result is still happening from time to time for me. I am aware of the pains of running multiple similar browser extensions simultaneously, but I like the audio compressor of FFZ too much too fully disable one or the other 😅 

As PualMage said above, usually a full browser restart fixes it, but it's common enough to be a bit annoying.

Love the extension though, great work!
