### ISSUE TITLE
[Bug] Youtube: Mousing over zero-width emote pushes base emotes down

### ISSUE THREAD

**Issue by robmonte** [SevenTV/Extension#155]
**Describe the bug**
Zero-width emotes are pushing down the underlying emote below the edge of the chat line when you mouse over them.

**To Reproduce**
1. Go to a youtube stream chat
2. Enter an emote followed by a zero-width emote
3. Send the message
4. Mouse over the emotes to display the pop-up box, then observe the emote placement.

**Expected behavior**
The emotes should not move on mouseover.

**Version:**
2.0.0

**Screenshots**
![image](https://user-images.githubusercontent.com/17119716/135015801-ed26da7b-8eb8-442e-9578-1f5d15762985.png)

**Comment by Cryptizism** [comment]
I believe that this issue has been resolved since, I can no longer replicate this issue. Can you?

**Comment by robmonte** [comment]
It still happens for me:
![emotes](https://user-images.githubusercontent.com/17119716/160218927-16133a7f-f233-4fb6-9cb5-86a453c70a26.gif)

**Comment by Cryptizism** [comment]
I can't personally replicate this issue, my thought is that something is being added to the div and it's pushing the emote down since its position is relative but the zero-width is also relative so I've got no clue what it could be. Maybe conflicting with another extension?

**Comment by robmonte** [comment]
Outside of trying with safe mode or another browser, I'm not familiar with what I could do to provide more info. If I get some time soon, I'll try the above stuff.
