### ISSUE TITLE
[BUG] Platform selection during installation doesnt allow for de-selecting Twitch

### ISSUE THREAD

**Issue by PaulVicino** [SevenTV/Extension#702]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest nightly version

- [X] I am using the latest nightly version

### What browsers are you seeing the problem on?

Firefox

### Current Behavior

When I'm installing 7tv, and unselect Twitch in the "select platform" step, 7tv still gets installed for the twitch domain.

I know its bizarre that I only want 7tv on Kick and not Twitch, but 7tv interferes with the filtering functionality of FrankerFaceZ on twitch because a 7tv profile gets added to FFZ which overrides some FFZ settings.

### Expected Behavior

7tv should only get installed for the platform domains that I select (in this case, only being Kick)

### Steps To Reproduce

While installing 7tv, deselect Twitch and Youtube. Finish the installation process and refresh twitch browser.

**Comment by Wilkolicious** [comment]
Looks like this got fixed at some point (only tested in Brave).  I can deselect Twitch and keep using FFZ.

**Comment by PaulVicino** [comment]
I dont think its fixed yet. I tried deselecting twitch, and im still seeing the 7tv icon on the top right of the twitch navbar after refreshing. If I deselect twitch, it should not be not be enabled on that domain. Its also still interfering with the filtering capabilities of FFZ.

**Comment by Wilkolicious** [comment]
Just to clarify how I got it working in Brave (but might be applicable to other browsers using Chromium):

1. Install the extension
2. Go into the extension options and disable "Automatically allow access on the following sites"
3. Run the onboarding setup by clicking "Extension options" from the extension settings page
4. De-selecting Twtich from the options
5. Finishing the onboarding setup
6. Should now look like the screenshot below

<img width="686" alt="image" src="https://github.com/SevenTV/Extension/assets/16191979/3157218b-aad3-48e6-9d95-21f9935a2521">

**Comment by gabuch2** [comment]
Just installed the extension on Firefox and I wanted the extension only for Kick, I wish it was fixed, it's annoying to have to deactivate 7TV every time you're on Twitch because of this.

**Comment by MariusGrandeAndersen** [comment]
If you really want to have a workaround on Chrome you can do this

1. download [Chrome Extension Source Viewer](https://chrome.google.com/webstore/detail/jifpbeccnghkjeaalbbjmodiffmgedin)
2. Go to [7TV](https://chrome.google.com/webstore/detail/7tv/ammjkodgmmoknidbanneddgankgfejfh) and download the extension with Chrome Extension Source Viewer as zip
3. extract and open manifest.json
4. search and replace "*://*.twitch.tv/*" with "*://*.kick.com/*"
5. open chrome://extensions/ and click the button on top "Load unpacked extension" and point to the local folder you unziped on step 3

**Comment by losinggeneration** [comment]
> This is because firefox uses twitch as the default `host_permissions` and cannot be removed unless the extension is updated to use a different `host_permissions`
> 
> ![image](https://user-images.githubusercontent.com/90581578/254271334-ef46081e-8f29-47d7-aa8e-b7023bc1bb91.png)

Host permissions are not mandatory: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/host_permissions

With that in mind, this might be as simple as moving the `*://*.twitch.tv/*` string from `host_permissions` to the `optional_host_permissions` array and removing the `host_permissions` variable (and references):
https://github.com/SevenTV/Extension/blob/master/manifest.config.ts#L66-L96
```ts
		// By default the extension is enabled only on Twitch
		host_permissions: ["*://*.twitch.tv/*"],
		permissions: ["scripting", "storage", "activeTab"],
		optional_permissions: ["management"],

		// Declare YouTube as an optional host permission
		optional_host_permissions: ["*://*.youtube.com/*", "*://*.kick.com/*", "*://*.7tv.app/*", "*://*.7tv.io/*"],

		web_accessible_resources: [
			{
				resources: ["site.js", "site.js.map", "content.js.map", "worker.js", "index.html", "assets/*"],
				matches: ["*://*.twitch.tv/*", "*://*.youtube.com/*", "*://*.kick.com/*"],
			},
		],
	} as Manifest.WebExtensionManifest & MV3HostPermissions;

	if (opt.mv2) {
		// if dev set manifest to version 2
		manifest.manifest_version = 2;

		manifest.background = {
			scripts: ["background.js"],
		};
		manifest.browser_action = manifest.action;

		// Host permissions -> permissions
		manifest.permissions = [...(manifest.permissions ?? []), ...(manifest.host_permissions ?? [])];
		manifest.optional_permissions = [
			...(manifest.optional_permissions ?? []),
			...(manifest.optional_host_permissions ?? []),
		];
```

However, I've never really done much with extension programming & permissions management, so my assumptions here may not be correct. If that sounds reasonable, I could open a PR for that change.

**Comment by AnatoleAM** [comment]
At this time disabling twitch won't be supported, since in order to do this, the extension would need to be updated to make twitch.tv optional, which would require a completely different installation flow.
